LTO_ENABLE = yes # reduce firmware size
NKRO_ENABLE = yes
STENO_ENABLE = yes
DEBOUNCE_TYPE = sym_defer_pk
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = no
COMMAND_ENABLE = no


RAW_ENABLE = yes